/**
 * BUILD-TIME ENV INJECTION
 * Reads .env and generates electron/env-config.js with credentials baked in.
 * This file is bundled inside the .asar archive (binary), so the keys
 * are NOT left as plain-text files in the installation directory.
 *
 * Usage: node scripts/inject-env.js  (called automatically by electron:build)
 */

const fs = require('fs');
const path = require('path');

const envPath = path.join(__dirname, '..', '.env');
const outputPath = path.join(__dirname, '..', 'electron', 'env-config.js');

let envVars = {};

try {
  const envContent = fs.readFileSync(envPath, 'utf8');
  envContent.split(/\r?\n/).forEach(line => {
    const match = line.match(/^\s*([\w.-]+)\s*=\s*(.*)?$/);
    if (match) {
      let value = (match[2] || '').trim();
      if (value.startsWith('"') && value.endsWith('"')) value = value.slice(1, -1);
      if (value.startsWith("'") && value.endsWith("'")) value = value.slice(1, -1);
      envVars[match[1]] = value;
    }
  });
  console.log(`✅ Read ${Object.keys(envVars).length} vars from .env`);
} catch (e) {
  console.warn('⚠️  .env not found — generating empty env-config.js (Google Drive will be disabled in production)');
}

// Generate the config module
const output = `// AUTO-GENERATED by scripts/inject-env.js at build time.
// Do NOT edit manually — changes will be overwritten on next build.
// Do NOT commit this file to version control.
module.exports = ${JSON.stringify(envVars, null, 2)};
`;

fs.writeFileSync(outputPath, output, 'utf8');
console.log(`✅ Wrote env-config.js with ${Object.keys(envVars).length} keys`);
